### ISSUE TITLE
Don't install the .exe

### ISSUE THREAD

**Issue by peter9811** [p-yukusai/PyWall#12]
Trying to install the last version,

![image](https://user-images.githubusercontent.com/22783445/168428053-487c3d23-e1bc-4ae4-93f9-9aaa757b3761.png)

**Comment by peter9811** [comment]
I'm on Windows 11, i tried install double click and too right click and admin priviligies

**Comment by p-yukusai** [comment]
Fixed on the [latest release](https://github.com/p-yukusai/PyWall/releases/tag/v1.6), please tell me if it works out for you 😄

**Comment by peter9811** [comment]
> Fixed on the [latest release](https://github.com/p-yukusai/PyWall/releases/tag/v1.6), please tell me if it works out for you 😄

Aparently now works perfect the .exe. Thanks
