### ISSUE TITLE
Option to block incoming connections 

### ISSUE THREAD

**Issue by peter9811** [p-yukusai/PyWall#14]
Maybe is possible add to suboption to block in connection, out connection and in-out connections 

Thanks

**Comment by peter9811** [comment]
Some app have independent .exe that download ads to show, I want to block this connections

**Comment by p-yukusai** [comment]
I'm afraid I don't quite understand what you want, in brief, PyWall creates an Outbound rule in the Windows Firewall that prohibits internet access to an specific application, and if I understood you correctly, this is what you wish to do with your executable.
As such, please elaborate further.

**Comment by peter9811** [comment]
(Sorry, English is not my mother tongue) 

What I am trying to say, is that I would like the context menu to also be able to block the incoming connections of the applications, normally what is done is that the outgoing connections are blocked. 

I follow, because some apps have their .exe that run to download things in the background, whether it's updates, advertising, or anything else.

**Comment by peter9811** [comment]
Maybe something like a sub menu that allows you to block outgoing connections, inbound connections, or both. And that it is not necessary to open the application, simply from the context menu 

Thank you very much for PyWall

**Comment by p-yukusai** [comment]
Oh, so you also wish to make it so it creates an Inbound rule, should be easy enough 😄 . Whenever I have the time I'll add it as an option in the Context menu and the GUI, thanks for liking my small app!

**Comment by peter9811** [comment]
Thank you for the application. It works quite well, really the only thing I would like is that option to also block incoming connections

I have a question, how does connection blocking work for folders?
Does it block connection to what type of files .exe, .dll, .msi or does it block all documents inside the folder?

Maybe a plugin to see what processes are using the internet would be great

**Comment by p-yukusai** [comment]
It does work for blocking folders, you may find answers to most of your questions in the readme, but in short, you can just right click a folder and, if you installed the shell extension from the GUI, PyWall will recursively block or allow all matches, bare in mind that you can add type suffixes (.dll, .msi, etc) that you wish to allow and filenames that you wish to ignore from the settings menu.

Also, you may find [Process Hacker](https://github.com/processhacker/processhacker) useful for finding out everything that's accessing the internet or being directed by the Firewall.

**Comment by peter9811** [comment]
Thanks for the Process Hacker tip, I used it a lot before, but I didn't have it in mind, I was able to check some processes that were connecting and I didn't have them blocked.

I've also reviewed how locking via folders works, and you're right. Only I hadn't tried it, because I thought it was going to block all the files inside and the subfolders, but what I wanted to block is made up of more than 2 thousand files, haha, maybe my PC would have frozen

**Comment by p-yukusai** [comment]
Yeah be careful with that, you may enable or disable the search of sub-folders, among other things, from the GUI :)

**Comment by p-yukusai** [comment]
Option added in [release v1.7](https://github.com/p-yukusai/PyWall/releases/tag/v1.7), thanks for your patronage 😄

**Comment by peter9811** [comment]
> Option added in [release v1.7](https://github.com/p-yukusai/PyWall/releases/tag/v1.7), thanks for your patronage 😄

THAANKS, you're the best 
I'm going to test it right now

**Comment by peter9811** [comment]
I had one problem 
![image](https://user-images.githubusercontent.com/22783445/169160659-80461aff-bcab-4fbc-b046-f6d94570a385.png)

**Comment by peter9811** [comment]
Maybe because I'm doing on C partition, PyWall question to grant admin permissions, but I don't know the reason

**Comment by p-yukusai** [comment]
The command to create or delete firewall rules ```netsh advfirewall firewall``` requires elevation to work, that's why PyWall asks for admin permissions.
Regarding your problem, PyWall will not create or delete rules for files without suffixes or with a suffix that is not in the accepted file types, since if your file lacks a suffix or it's not an executable, it probably won't connect to the internet.
If you wish to expand the suffixes that PyWall accepts you may do so in the GUI.

**Comment by peter9811** [comment]
I have no problem with me asking for administrator permissions, because I know you need them and from the beginning I asked for them

And I don't think it's a problem with the file extension, because it's an ".exe" executable and that one had already blocked it, I don't know if having that duplicate is not able to generate the block, although I tried the 3 options. Block inbound, outbound, and both connections. But it didn't work with any of them.

**Comment by p-yukusai** [comment]
I'm afraid I cannot replicate the bug on my end, please send me the path used to test it.
One thing that may work is to delete the PyWall folder in your documents, please try this later one first.

**Comment by peter9811** [comment]
I deleted the folder on Documents and don't fixed it. The app restart like new
The path is, C:\Program Files (x86)\Captura. Inside one .exe and don't blocked it

**Comment by p-yukusai** [comment]
I've managed to replicate it, please create a new issue to track that bug, for now I'll lock this one since it's gotten way too long 😃

**Comment by p-yukusai** [comment]
Bug fixed in latest release
