### ISSUE TITLE
Not removing the config files when uninstalling

### ISSUE THREAD

**Issue by peter9811** [p-yukusai/PyWall#27]
Hello, i was modifying the config file (inside the app UI) and by mistake I just put a comment 
![Screenshot 2024-10-13 130852](https://github.com/user-attachments/assets/3142c8e5-3630-42fb-b42f-62f76289ecc8)

and now the app don't open, I tried uninstalling by HiBit and IObit uninstaller, but don't fix the problem 

Can I know where is the path of the config.ini file or maybe create a update to remove the config file when is uninstalled too?

Thanks and sorry, haha

**Comment by p-yukusai** [comment]
The config is on your documents, the path being `%userprofile%/Documents/PyWall`
I'll fix the error later, thank you for the report.

**Comment by p-yukusai** [comment]
Fixed 
https://github.com/p-yukusai/PyWall/releases/tag/v1.7.2.1

**Comment by peter9811** [comment]
Thanks. You're the best, haha
Sorry to bring "bugs" every couple of months

**Comment by peter9811** [comment]
@p-yukusai sorry for the tag. I just update, I didn't delete the config file just to check. I gonna check 
![image](https://github.com/user-attachments/assets/a70433ba-09c4-481f-9e3c-e33aa21e628c)

I just remove the file and work fine, but maybe cannot handle the error on the config (anyway is just specific in my case)
